# Generated by Django 2.1.7 on 2019-10-01 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lsd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "laste_edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_number", models.CharField(max_length=100)),
                ("article_revision", models.IntegerField()),
                ("article_description", models.TextField()),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "families",
                    models.ManyToManyField(related_name="families", to="lsd.Family"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "laste_edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("version_string", models.TextField()),
                ("version_major", models.IntegerField()),
                ("version_minor", models.IntegerField()),
                ("version_micro", models.IntegerField()),
                ("version_build", models.IntegerField()),
                ("version_commit", models.CharField(max_length=100)),
                ("git_path", models.CharField(max_length=512)),
                ("bin_path", models.CharField(max_length=512)),
                ("doc_path_html", models.CharField(max_length=512)),
                ("doc_path_pdf", models.CharField(max_length=512)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "laste_edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AddField(
            model_name="product",
            name="linked_software",
            field=models.ManyToManyField(related_name="releases", to="lsd.Release"),
        ),
        migrations.AddField(
            model_name="family",
            name="product_groups",
            field=models.ManyToManyField(
                related_name="product_groups", to="lsd.ProductGroup"
            ),
        ),
    ]
