# Generated by Django 2.1.7 on 2019-12-10 07:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lsd", "0002_auto_20191001_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="status",
            field=models.CharField(
                choices=[("d", "Draft"), ("r", "Released"), ("w", "Withdrawn ")],
                default="d",
                max_length=1,
            ),
        ),
    ]
