# Generated by Django 2.1.7 on 2020-07-06 11:02


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lsd", "0004_auto_20200622_1108"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("version", models.CharField(max_length=100)),
                (
                    "usage_status",
                    models.CharField(
                        choices=[("a", "Approved"), ("l", "locked")],
                        default="l",
                        max_length=1,
                    ),
                ),
                (
                    "release_status",
                    models.IntegerField(
                        choices=[(0, "Basic Integrity"), (1, "SIL1"), (2, "SIL2")],
                        default=0,
                    ),
                ),
                ("comment", models.TextField()),
                ("system_requirements", models.TextField()),
                ("license_model", models.TextField()),
                ("license_host_path", models.CharField(max_length=512)),
                (
                    "classification",
                    models.IntegerField(
                        choices=[(1, "T1"), (2, "T2"), (3, "T3")], default=None
                    ),
                ),
                ("specification_path", models.CharField(max_length=512)),
                ("manual_path", models.CharField(max_length=512)),
                ("proof_of_compliance_path", models.CharField(max_length=512)),
                ("characterization_path", models.CharField(max_length=512)),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "proxy_user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proxy_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="release",
            name="linked_tools",
            field=models.ManyToManyField(related_name="releases", to="lsd.Tool"),
        ),
    ]
