# Generated by Django 2.1.7 on 2020-07-08 16:29


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lsd", "0005_auto_20200706_1102"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="developer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="developer_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="process_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="using_releases",
                to="lsd.Release",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="responsible_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_user_release",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="sil_level",
            field=models.IntegerField(
                choices=[(0, "Basic Integrity"), (1, "SIL1"), (2, "SIL2")], default="0"
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="software_type",
            field=models.CharField(
                choices=[("i", "Internal"), ("e", "External"), ("t", "Third Party")],
                default="i",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="tester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tester_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="verifier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verifier_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="laste_edited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="last_edit_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="classification",
            field=models.IntegerField(
                choices=[(1, "T1"), (2, "T2"), (3, "T3")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="proxy_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proxy_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="responsible_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_user_tool",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
