# Generated by Django 2.1.7 on 2020-07-21 16:36, modified by shentges


from django.db import migrations, models


class Migration(migrations.Migration):
    # Atomic has to be set to false to prevent
    # NotSupportedError:Renaming the 'posts_file' table while in a transaction is not supported on
    # SQLite because it would break referential integrity.
    atomic = False

    dependencies = [
        ("lsd", "0006_remove_product_category"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Product",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Product",
                    table="products_product",
                ),
            ],
        ),
    ]
