# Generated by Django 2.1.7 on 2020-07-28 09:48
# modified by J. Luelsdorf


from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lsd", "0007_delete_product"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Tool",
                ),
                migrations.AlterField(
                    model_name="release",
                    name="linked_tools",
                    field=models.ManyToManyField(
                        related_name="releases", to="tools.Tool"
                    ),
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Tool", table="tools_tool"),
            ],
        )
    ]
