# Generated by Django 2.1.7 on 2020-07-29 06:24
# modified by J. Luelsdorf


from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("products", "0002_AlterField_linked_software_to_softwareRelease"),
        ("lsd", "0008_AlterModelTable_location_of_Tool"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="release",
                    name="developer",
                ),
                migrations.RemoveField(
                    model_name="release",
                    name="laste_edited_by",
                ),
                migrations.RemoveField(
                    model_name="release",
                    name="linked_tools",
                ),
                migrations.RemoveField(
                    model_name="release",
                    name="process_version",
                ),
                migrations.RemoveField(
                    model_name="release",
                    name="responsible_user",
                ),
                migrations.RemoveField(
                    model_name="release",
                    name="tester",
                ),
                migrations.RemoveField(
                    model_name="release",
                    name="verifier",
                ),
                migrations.DeleteModel(
                    name="Release",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Release", table="software_release")
            ],
        )
    ]
