# Generated by Django 2.1.7 on 2020-07-29 06:24
# modified by J. Luelsdorf


from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        (
            "products",
            "0003_CreateModel_Family_and_ProductGroup_AlterField_product_and_family",
        ),
        ("lsd", "0009_AlterModelTable_location_of_Release"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="family",
                    name="laste_edited_by",
                ),
                migrations.RemoveField(
                    model_name="family",
                    name="product_groups",
                ),
                migrations.RemoveField(
                    model_name="productgroup",
                    name="laste_edited_by",
                ),
                migrations.DeleteModel(
                    name="Family",
                ),
                migrations.DeleteModel(
                    name="ProductGroup",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name="Family", table="products_family"),
                migrations.AlterModelTable(
                    name="ProductGroup", table="products_productgroup"
                ),
            ],
        )
    ]
