# Generated by Django 2.1.7 on 2020-10-22 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import licenses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_level_license",
                    models.IntegerField(
                        auto_created=True,
                        choices=[(0, "RED"), (1, "YELLOW"), (2, "GREEN")],
                        default=0,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("annotation", models.CharField(max_length=512)),
                (
                    "originalText",
                    models.FileField(
                        upload_to=licenses.models.license_file_directory_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_level",
                    models.IntegerField(
                        choices=[(0, "RED"), (1, "YELLOW"), (2, "GREEN")], default="0"
                    ),
                ),
                ("paragraph_text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_level_section",
                    models.IntegerField(
                        auto_created=True,
                        choices=[(0, "RED"), (1, "YELLOW"), (2, "GREEN")],
                        default=0,
                    ),
                ),
                ("annotation", models.TextField()),
                (
                    "linked_paragraphs",
                    models.ManyToManyField(
                        related_name="Section", to="licenses.Paragraph"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="license",
            name="linked_sections",
            field=models.ManyToManyField(
                blank=True, related_name="License", to="licenses.Section"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="request_User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
