# Generated by Django 2.1.7 on 2020-12-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='usage',
            field=models.CharField(choices=[('static', 'static'), ('dynamic', 'dynamic'), ('unkown', 'unkown'), ('rootfs', 'rootfs')], default='u', max_length=1),
        ),
    ]
