# Generated by Django 2.1.7 on 2021-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20201216_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='usage',
            field=models.CharField(choices=[('rootfs', 'rootfs'), ('static', 'static'), ('dynamic', 'dynamic'), ('unkown', 'unkown')], default='u', max_length=1),
        ),
    ]
