""""
Generated by 'django-admin startapp licenses' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/
"""
from django.apps import AppConfig


class LicensesConfig(AppConfig):
    name = "licenses"
