# Generated by Django 2.1.7 on 2020-07-21 16:40, modified by shentges.


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lsd", "0007_delete_product"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Product",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=100)),
                        ("article_number", models.CharField(max_length=100)),
                        ("article_revision", models.IntegerField()),
                        ("article_description", models.TextField()),
                        ("content", models.TextField()),
                        (
                            "date_posted",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        (
                            "author",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "families",
                            models.ManyToManyField(
                                related_name="families", to="lsd.Family"
                            ),
                        ),
                        (
                            "linked_software",
                            models.ManyToManyField(
                                related_name="releases", to="lsd.Release"
                            ),
                        ),
                    ],
                ),
            ],
            # Table already exists. See lsd/migrations/0007_delete_product.py
            database_operations=[],
        ),
    ]
