# Generated by Django 2.1.7 on 2020-07-29 06:24
# modified by J. Luelsdorf


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("software", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="product",
                    name="linked_software",
                    field=models.ManyToManyField(
                        related_name="releases", to="software.Release"
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
