# Generated by Django 2.1.7 on 2020-07-29 06:24
# modified by J. Luelsdorf


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Release",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=100)),
                        ("version_string", models.TextField()),
                        ("version_major", models.IntegerField()),
                        ("version_minor", models.IntegerField()),
                        ("version_micro", models.IntegerField()),
                        ("version_build", models.IntegerField()),
                        ("version_commit", models.CharField(max_length=100)),
                        ("git_path", models.CharField(max_length=512)),
                        ("bin_path", models.CharField(max_length=512)),
                        ("doc_path_html", models.CharField(max_length=512)),
                        ("doc_path_pdf", models.CharField(max_length=512)),
                        (
                            "date",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("d", "Draft"),
                                    ("r", "Released"),
                                    ("w", "Withdrawn"),
                                ],
                                default="d",
                                max_length=1,
                            ),
                        ),
                        (
                            "sil_level",
                            models.IntegerField(
                                choices=[
                                    (0, "Basic Integrity"),
                                    (1, "SIL1"),
                                    (2, "SIL2"),
                                ],
                                default="0",
                            ),
                        ),
                        (
                            "software_type",
                            models.CharField(
                                choices=[
                                    ("i", "Internal"),
                                    ("e", "External"),
                                    ("t", "Third Party"),
                                ],
                                default="i",
                                max_length=1,
                            ),
                        ),
                        (
                            "developer",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="developer_user",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "laste_edited_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="last_edit_user",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "linked_tools",
                            models.ManyToManyField(
                                related_name="releases", to="tools.Tool"
                            ),
                        ),
                        (
                            "process_version",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="using_releases",
                                to="software.Release",
                            ),
                        ),
                        (
                            "responsible_user",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="responsible_user_release",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "tester",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="tester_user",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "verifier",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="verifier_user",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
            ],
            database_operations=[],
        )
    ]
