# Generated by Django 2.1.7 on 2020-10-22 12:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
        ("licenses", "0001_initial"),
        ("software", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="linked_licenses",
            field=models.ManyToManyField(
                blank=True, related_name="licenses", to="licenses.License"
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="linked_packages",
            field=models.ManyToManyField(
                blank=True, related_name="package", to="packages.Package"
            ),
        ),
    ]
